export const SET_CONSTANTS = 'SET_CONSTANTS';
export const SET_PREDICATES = 'SET_PREDICATES';
export const SET_FUNCTIONS = 'SET_FUNCTIONS';

export const LOCK_CONSTANTS = 'LOCK_CONSTANTS';
export const LOCK_PREDICATES = 'LOCK_PREDICATES';
export const LOCK_FUNCTIONS = 'LOCK_FUNCTIONS';

export const SET_CONSTANT_VALUE = 'SET_CONSTANT_VALUE';
export const SET_PREDICATE_VALUE_TEXT = 'SET_PREDICATE_VALUE_TEXT';
export const SET_PREDICATE_VALUE_TABLE = 'SET_PREDICATE_VALUE_TABLE';
export const SET_FUNCTION_VALUE_TEXT = 'SET_FUNCTION_VALUE_TEXT';
export const SET_FUNCTION_VALUE_TABLE = 'SET_FUNCTION_VALUE_TABLE';

export const LOCK_CONSTANT_VALUE = 'LOCK_CONSTANT_VALUE';
export const LOCK_PREDICATE_VALUE = 'LOCK_PREDICATE_VALUE';
export const LOCK_FUNCTION_VALUE = 'LOCK_FUNCTION_VALUE';

export const SET_VARIABLES_VALUE = 'SET_VARIABLES_VALUE';
export const SET_DOMAIN = 'SET_DOMAIN';
export const LOCK_DOMAIN = 'LOCK_DOMAIN';
export const LOCK_VARIABLES = 'LOCK_VARIABLES';

export const IMPORT_APP = 'IMPORT_APP';

export const ADD_EXPRESSION = 'ADD_EXPRESSION';
export const REMOVE_EXPRESSION = 'REMOVE_EXPRESSION';
export const SET_EXPRESSION_ANSWER = 'SET_EXPRESSION_ANSWER';
export const LOCK_EXPRESSION_VALUE = 'LOCK_EXPRESSION_VALUE';
export const LOCK_EXPRESSION_ANSWER = 'LOCK_EXPRESSION_ANSWER';
export const CHECK_SYNTAX = 'CHECK_SYNTAX';

export const TOGGLE_EDIT_TABLE = 'TOGGLE_EDIT_TABLE';
export const TOGGLE_TEACHER_MODE = 'TOGGLE_TEACHER_MODE';
